services:
  odoo:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: odoo-custom:16
    ports:
      - "8070:8069"
      - "8073:8072"
    entrypoint: /entrypoint.sh
    volumes:
      - ./addons:/mnt/extra-addons # Seus mÃ³dulos customizados
      - ./l10n-brazil:/mnt/l10n-brazil
      - ./account-payment:/mnt/account-payment
      - ./bank-payment:/mnt/bank-payment
      - ./product-attribute:/mnt/product-attribute
      - odoo-data:/var/lib/odoo
      - ./docker/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo_password
      - WORKERS=0
      - LONGPOLLING_PORT=8072
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8069/web/database/selector >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  odoo-data: